<p>&nbsp;</p>
<p>Updated April 2010</p>
<h2>AXIS MAPS, LLC PRIVACY POLICY</h2>
<p>Axis Maps, LLC ("Axis Maps" or "we" or "us") desires to protect the privacy of our online guests at indiemapper.com (the "Site").  This privacy policy ("Privacy Policy") is intended to provide you notice of our information management practices, including the types of information gathered and how it is used and safeguarded.  Your use of this Site constitutes acceptance of this Privacy Policy and the <a href="legal.php?l=terms">Terms of Use</a>, which are hereby incorporated by reference.</p>
<h3>Collection and Our Use of Information</h3>
<p>We will collect no personally identifiable information about you when you visit our Site unless you voluntarily choose to provide that information to us.  Any personally identifiable information that you provide to us via our Site will be used only for such purposes as are described either in this Privacy Policy or at the point of collection, such as to respond to your questions or comments, to register, to send you a requested brochure or to otherwise send information to you. </p>
<h3>Protection of Children's Personal Information</h3>
<p>We do not publish content that is targeted to children.  We do not intend to collect personally identifiable information from anyone under 13 and will not knowingly collect, maintain, or disclose such information.  If you are under 13, you should not enter any personally identifiable information about yourself on our Site.  If you are a parent or guardian who has discovered that your child under the age of 13 has submitted his or her personally identifiable information without your permission or consent, we will make reasonable efforts to remove the information from our database, at your written request.  To request the removal of your child's information, please send us an e-mail at info@axismaps.com and be sure to include in your message the same information, including e-mail address that your child submitted.</p>
<h3>Aggregate and Statistical Data</h3>
<p>We may collect certain aggregate data called web log information (such as your web browser, operating system, pages visited, etc.) and use cookies when you visit the Site (collectively, the "Aggregate and Statistical Data"). For instance, when you visit the Site, our web server will automatically recognize some non-personal information, including but not limited to the date and time you visited the Site, the pages you visited, the referrer (the website you came from), the type of browser you are using, the type of operating system you are using, and the domain name and address of your Internet service provider. Neither the web log information nor cookies (as discussed below) collects any personal information. They do not contain personal information, such as your name or e-mail address, and in no way are used to identify our users. Aggregate and Statistical Data helps us design the Site, to identify popular features, and for other managerial purposes.</p>
<h3>Use of Cookies</h3>
<p>We may store cookies on your computer to improve the quality of your visit to our Site. A cookie is a small amount of data that is sent to your browser from a web server and stored on your computer's hard drive. We use "cookie" technology for several purposes. First, we use it to track general information about our users. The information collected through cookies is non-personally identifiable information and we use this information for statistical and market research purposes. We also use cookies to establish a link between your computer and Axis Maps. This link assures that, when you return to Axis Maps, you will be able to log in without the necessity of providing your password, or help us to avoid asking for the same information on your return visits to the Site.  You have choices with respect to cookies. By modifying your browser preferences, you have the choice to accept all cookies, to be notified when a cookie is set, or to reject all cookies. Refer to your browser’s instructions or "Help" button to learn more about cookies.</p>
<h3>Personally Identifiable Information</h3>
<p>You may also be asked to provide personally identifiable information on the Site which may include your name, address, telephone number, credit card number and e-mail address (your "Personally Identifiable Information"). This information may be gathered when feedback or e-mails are sent to the Site, when you register for an account, use our service, post information on the Site or use a credit card to pay for any payments. In all cases, you have the option of providing us with the Personally Identifiable Information, though certain services and features may not be available to you if you do not provide personally identifiable information. You agree that we may contact you to provide you with information we believe may be of interest to you. At that time, you will be offered the opportunity to opt out of this service. You may remove your e-mail address from the list at any time by clicking on the unsubscribe link provided at the bottom of every e-mail. We will not rent or sell your Personally Identifiable Information or share it with anyone except as otherwise stated in this Privacy Policy. </p>
<h3>Non-Personally Identifiable Information</h3>
<p>Data that is not personally identifiable, such as answers to surveys, comments, ideas and suggestions that do not include your personally identifying information, are deemed to be non-confidential, and we are free to disclose and use such data, without any obligation whatsoever to you for any purpose and through any means.</p>
<h3>Use and Sharing of Information</h3>
<p>We may share your Personally Identifiable Information with our vendors, contractors or partners in connection with services that these individuals or entities perform for or with us, or when it is required to complete a customer-requested transaction, delivery or to provide services. These vendors, contractors or partners are restricted from using this data in any way other than to provide services for us, and they may not share or resell this data. The services they provide may include such activities as direct mailing, fulfillment services (such as billing and payment) and e-mail campaigns. We may use your Personally Identifiable Information along with the Aggregate and Statistical Data to improve our marketing and promotional efforts; to statistically analyze Site usage; to improve our content and product offerings; and to customize the Sites' content, layout and services.  We believe these uses allow us to improve the Site and better tailor it to meet our visitors' needs.</p>
<p>We also may disclose Personally Identifiable Information about you to a subsequent owner or operator of our Site if we assign our rights and obligations regarding any of your information at the time of a merger, acquisition, or sale of all or substantially all of our assets or the Site's assets and/or services to a subsequent owner or operator.  You will be deemed to have consented to the disclosure to, and use by, a subsequent owner or operator of such web site, and your continued use of the Site signifies your agreement to be bound by the Terms of Use and Privacy Policy of the Site's subsequent owner or operator.</p>
<p>We may also disclose Personally Identifiable Information to third parties in the following instances: 1) we have been given your consent to disclose; 2) we have previously informed you of the disclosure, including by means of our Privacy Policy; 3) we are required by law or court order to disclose, or we believe in good faith that the law requires it; 4) disclosure is necessary to identify, contact, or bring legal action against, someone who may cause or be causing harm to, or interference with, our rights or property, other Site users, or anyone else; or 5) to respond to an inquiry, request or complaint that you have made.  We may also use IP addresses in cooperation with internet service providers to identify users if we deem it necessary to comply with laws, to enforce compliance with this Privacy Policy or our Terms of Use, or to protect our Site, customers, or others.</p>
<h3>Security</h3>
<p>We will make reasonable efforts to ensure that whatever information you provide will be maintained in a secure environment. Unfortunately, no data transmission over the Internet can be guaranteed to be 100% secure. As a result, while we strive to protect your personal information, we cannot guarantee the security of any information you transmit to us or from our Site, and you provide such information at your own risk. </p>
<h3>Correct or Remove Information</h3>
<p>If you have submitted Personally Identifiable Information through the Site and would like that information deleted from our records, you would like to update or correct that information or you have and questions or comments regarding our Policy, please contact us at our e-mail address, info@axismaps.com with the subject line "Privacy Policy Question", and provide us with your name, postal address and any other information necessary to respond to your question. We will use commercially reasonable efforts to make corrections or remove your name and address from future mailings.</p>
<h3>Links to Other Sites </h3>
<p>Axis Maps may from time to time offer links to other sites from sites within the Axis Maps domain. Axis Maps has no control over these external sites or their content, and cannot be held responsible for any actions they may take or any information they might collect. You may arrive at one of these sites through clicking on a banner advertisement, as part of a co-branding arrangement, or simply by selecting a link on an Axis Maps web page. You should be aware that this Privacy Policy does not apply to your use of these sites.  If you provide any information to such sites, different rules regarding the collection and use of your Personally Identifiable Information may apply. Before using these linked sites, you may wish to review their privacy policies to understand how they treat privacy, security, data collection, and distribution. These sites might issue their own cookies or collect data or personal information. Use caution when visiting an external site.</p>
<h3>Changes to Policy</h3>
<p>We may, at any time, revise these policies by updating this posting.  Your continued use of this Site indicates your acceptance of all revisions and you should, therefore, periodically visit this page to review these policies for changes.  If you have any comments or questions about this policy, please contact us at info@axismaps.com.</p>
<h3>Consent to Processing in the United States</h3>
<p>By providing any personally identifiable information to Axis Maps pursuant to this Privacy Policy, all users, including, without limitation, users in the member states of the European Union, fully understand and unambiguously consent to this Privacy Policy and to the collection and processing of such information in the United States of America. The server on which this website is hosted may be outside the country from which you access this Site and may be outside your country of residence. Some of the uses and disclosures mentioned in this Privacy Policy may involve the transfer of your Personally Identifiable Information to various countries around the world that may have different levels of privacy protection than your country. By submitting your Personally Identifiable Information through this Site, you consent, acknowledge, and agree that we may collect, use, transfer, and disclose your Personally Identifiable Information as described in this Privacy Policy. If you do not consent to the terms of this Privacy Policy, please do not use this Site.</p>
<p>Effective Date of this Privacy Policy:   April 12, 2010.</p>