<p>&nbsp;</p>
<p>Updated April 2010</p>
<h2>AXIS MAPS, LLC WEB SITE TERMS AND CONDITIONS OF USE</h2>
<h3>Introduction</h3>
<p>Thank you for visiting Axis Maps' ("Axis Maps" or "we" or "us") Web site located at indiemapper.com (the "Site"). This page sets out the terms and conditions ("Terms and Conditions") which will govern your use of the Site and compliance with these rules is a condition to your use of the Site.  We reserve the right to modify these Terms and Conditions.  Accordingly, please review this page often.  Axis Maps will give notice of changes to the Terms and Conditions by posting the revised Terms and Conditions on this Site, together with the date the Terms and Conditions were last updated. Modifications will be effective immediately upon posting.  Your continued use of this Site indicates your agreement to be bound by the modified Terms and Conditions.  If you do not agree to be bound by the Terms and Conditions, promptly exit this Site.  If you have any questions regarding these Terms and Conditions, please email your questions to info@axismaps.com.</p>
<h3>Section A - User Information</h3>
<h4>User Information</h4>
<p>By using this Site, (1) you represent and agree that you are bound by these Terms and Conditions; and (2) you have read Axis Maps' <a href="legal.php?l=privacy">Privacy Policy</a> and consent to the use of your personal information by Axis Maps and others in accordance with the terms of and for the purposes set forth in Axis Maps' Privacy Policy.</p>
<h3>Section B - Ownership and Copyright</h3>
<h4>Ownership and Copyright</h4>
<p>All pages within this Site and any material made available for download are the property of Axis Maps, its subsidiaries, affiliates, vendor and/or licensors.  The Site is protected by United States and international copyright and trademark laws.  Any rights not expressly granted herein are reserved.</p>
<p>The contents of the Site, including without limitation the text, images, audio, and video, and any materials accessed through or made available for use or download through this site are copyrighted and may not be copied, distributed, modified, reproduced, published or used, in whole or in part, without the prior written consent of Axis Maps, except that you may download content from the Site to any single computer for your personal use only, provided you keep intact all copyright, trademark, and other proprietary notices and comply with any applicable end user license agreements.  No part of any content, form or document may be reproduced in any form or incorporated into any information retrieval system, electronic or mechanical, other than for your personal use (but not for resale or redistribution).</p>
<p>For purposes of these Terms and Conditions, any use of these materials on any other Web site is prohibited.  You do not acquire ownership rights to any content, document or other materials viewed through the Site.  The posting of information or materials on the Site does not constitute a waiver of any right in such information and materials.  All software used on this Site is the property of Axis Maps or its software suppliers and protected by United States and international copyright laws.</p>
<h3>Section C - License; Restrictions on Use</h3>
<h4>License; Restrictions on Use </h4>
<p>Axis Maps hereby grants you a limited, nonexclusive, revocable, and non-transferable license to use and access the Site, and print out the materials solely for your personal use, provided you retain all copyright and other proprietary notices, and pursuant to the requirements and restrictions of these Terms of and Conditions. If you have purchased an online subscription to the Site, it is personal to the individual whose name appears in the first and last name field of the subscription order form and it cannot be shared with or used by any other individual or entity. This license does not include any resale or commercial use of this Site or its contents; any collection and use of any product listings, descriptions, or any prices; any derivative use of this Site or its contents; any downloading or copying of account information for the benefit of another merchant; or any use of data mining, robots, or other data gathering and extraction tools. You may not otherwise reproduce, copy, modify, decompile, disassemble or reverse engineer any materials from this Site, and may not republish, upload, post, transmit, loan, rent, transfer, sell or otherwise distribute any materials from this Site in any form, for any purpose. The use of any such materials on any other Web site or network computer environment is also prohibited. You may not frame or utilize framing techniques to use, surround or enclose any of Axis Maps' names, trademarks, service marks, logo, or other proprietary information (including; images, text, page layout, or form) of Axis Maps and/or our affiliates or subsidiaries without Axis Maps' express written consent. You may not use any meta tags or any other "hidden text" utilizing Axis Maps' name or trademarks without the express written consent of Axis Maps. Notwithstanding the above, Axis Maps grants you the right download, print, distribute, and resell materials you created using the Site, provided you retain all copyright and other proprietary notices, and pursuant to the requirements and restrictions of these Terms of and Conditions. </p>
<p>As a condition of your use of this Web site, you warrant to Axis Maps that you will not use the Site for any purpose that is unlawful or prohibited by these Terms and Conditions. You also agree not to deep-link to the site for any purpose, unless specifically authorized by Axis Maps to do so.  If you breach any of these Terms and Conditions, your authorization to use this Site automatically terminates and you must immediately destroy any downloaded or printed materials.  Any rights not expressly granted by these Terms and Conditions or any applicable end user license agreements are reserved by Axis Maps. If you use the materials other than as permitted in this license, you will be violating Axis Maps' copyright and other proprietary rights.</p>
<p>In addition to the restrictions set forth herein, and unless specifically authorized in writing by Axis Maps, you may not use any information provided by or contained in the Site with any products, systems, or applications installed or otherwise connected to or in communication with vehicles, capable of vehicle navigation, positioning, dispatch, real time route guidance, fleet management or similar applications. You also may not use this information with or in communication with any mobile or wireless-connected electronic or computer devices, including without limitation cellular and smart phones, handheld computers, and any other personal computing devices.</p>
<h3>Section D - Trademark Notice</h3>
<h4>Trademark Notice</h4>
<p>Axis Maps and indiemapper are trademarks owned by Axis Maps and/ or its subsidiaries or affiliates. Axis Maps' trademarks may not be used in connection with any product or service that is not Axis Maps', in any manner that is likely to cause confusion among customers or in any manner that disparages or discredits Axis Maps.  All other trademarks and logos used in this Site are the trademarks, service marks or logos of their respective owners.  Axis Maps does not make any claims to the marks of others which might appear on the Site.  You gain no right to use any marks of Axis Maps or any other entity by virtue of your use of this Site.</p>
<h3>Section E - Confidential And Proprietary Information / Visitor Submissions</h3>
<h4>Confidential and Proprietary Information/Visitor Submissions</h4>
<p>Please refer to our <a href="legal.php?l=privacy">Privacy Policy</a> for an explanation of how we collect, maintain and use confidential and proprietary information from visitors to and users of our Site.  By accessing, using or browsing this Site, you acknowledge and understand that you have read, understand, and agree to be bound by our Privacy Policy.  If you do not agree with our Privacy Policy, do not use this Site.  All remarks, suggestions, ideas, graphics, or other information communicated to Axis Maps through its Site (collectively, the "Submission") will forever be the property of Axis Maps.  Axis Maps will not be required to treat any Submission as confidential, and will not be liable for any ideas for its business (including without limitation, product or advertising ideas) and will not incur any liability as a result of any similarities that may appear in future Axis Maps products or operations.  Without limitation, Axis Maps will have exclusive ownership of all present and future existing rights to the Submissions of every kind and nature, everywhere.  Axis Maps will be entitled to use the Submission for any commercial or other purpose whatsoever, without compensation to you or any other person sending the Submission.  You acknowledge that you are responsible for whatever material you submit, and you, not Axis Maps, have full responsibility for the message, including its legality, reliability, appropriateness, originality, and copyright.</p>
<p>You agree not to try to access and not to access any information through the Site which does not pertain to you and which you are not properly authorized to receive.  You agree that if you should access information about another individual or entity, or otherwise receive information you are not authorized to receive, or if you become aware that someone else has accessed or attempted to access information that person was not authorized to receive, you will immediately cease such unauthorized access, notify Axis Maps of the unauthorized access, and assist Axis Maps in identifying and correcting the circumstances which permitted such unauthorized access.  You will keep confidential all information you receive concerning another individual or entity confidential, shall not use such information, shall return such information to Axis Maps immediately, shall not transmit it to any other person or entity and shall not return it in any electronic or other form.</p>
<h3>Section F - Security</h3>
<h4>Security</h4>
<p>You may be required to enter a valid User I.D. and password ("Access Codes") to access certain areas of the Site or to purchase products.  It is your sole responsibility to monitor and control use of these Access Codes for all purposes.  You accept all responsibility for the security of your Access Codes, and utilization of the Site via the Access Codes.  You agree that you shall be solely liable for all authorized and unauthorized access using the Access Codes.   Do not disclose your Access Codes to anyone not authorized to act on your behalf.  Axis Maps cannot and will not be liable for any loss or damage arising from your failure to comply with this Section F. </p>
<h3>Section G- Forward Looking Statements</h3>
<h4>Forward-Looking Statements</h4>
<p>The Site may contain forward-looking statements regarding Axis Maps' business, customers, partners, future products and services or other factors that may affect future earnings or financial results.  Such statements involve risks and uncertainties, which could cause actual results to vary materially from those expressed in or indicated by the forward-looking statements.  Examples of these risks include delays in development, competitive service and product offerings, and lack of market acceptance.</p>
<h3>Section H -Disclaimer of Warranties</h3>
<h4>Disclaimer of Warranties</h4>
<p>Axis Maps DOES NOT WARRANT THAT THE SITE WILL BE UNINTERRUPTED OR ERROR-FREE, OR THAT DEFECTS IN THE SITE WILL BE CORRECTED, OR THAT THIS SITE OR THE SERVER THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. THIS SITE, INCLUDING ANY CONTENT OR INFORMATION CONTAINED WITHIN IT, AND ANY SITE-RELATED SERVICES, ARE PROVIDED "AS IS," AND "AS AVAILABLE" WITH ALL FAULTS. Axis Maps MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, AND SPECIFICALLY DISCLAIMS ANY SUCH WARRANTIES, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.  </p>
<p>AXIS MAPS SPECIFICALLY DISCLAIMS ALL LIABILITY FOR ERRORS OR OMISSIONS IN, OR THE MISUSE OR MISINTERPRETATION OF, ANY INFORMATION OBTAINED THROUGH THE SITE.  AXIS MAPS DOES NOT WARRANT THE ACCURACY, COMPLETENESS OR TIMELINESS OF THE INFORMATION OBTAINED THROUGH THE SITE.  </p>
<p>AXIS MAPS DOES NOT WARRANT THAT FILES AVAILABLE FOR DOWNLOAD WILL BE FREE OF VIRUSES, WORMS, TROJAN HORSES OR OTHER DESTRUCTIVE PROGRAMMING.  YOU ARE RESPONSIBLE FOR IMPLEMENTING PROCEDURES SUFFICIENT TO SATISFY YOUR NEEDS FOR DATA BACK UP AND SECURITY.  YOU AGREE THAT AXIS MAPS SHALL NOT BE LIABLE FOR ANY COSTS OR DAMAGES ARISING DIRECTLY OF INDIRECTLY FROM ANY SUCH CODE.  YOU ASSUME TOTAL RESPONSIBILITY AND RISK FOR YOUR USE OF THE SITE AND OF THE INTERNET, INCLUDING ANY SITE-RELATED SERVICES, AND HYPERLINKED WEB SITES.</p>
<p>NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY AXIS MAPS OR AXIS MAPS' AUTHORIZED REPRESENTATIVES SHALL CREATE A WARRANTY OR IN ANY WAY INCREASE THE SCOPE OF THIS WARRANTY.</p>
<p>CERTAIN STATE LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES. SOME OR ALL OF THE ABOVE DISCLAIMERS, EXCLUSIONS, OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MAY HAVE ADDITIONAL RIGHTS.</p>
<h3>Section I - Violation of the Terms and Conditions</h3>
<h4>Violation of the Term and Conditions</h4>
<p>You understand and agree that in Axis Maps' sole discretion, and without prior notice, Axis Maps may terminate your access to the Site, or exercise any other remedy available and remove any unauthorized user information, if Axis Maps believes that the information you provide has violated or is inconsistent with these Terms and Conditions, or violates the rights of Axis Maps, or any third party, or violates the law. You agree that monetary damages may not provide a sufficient remedy to Axis Maps for violations of these Terms and Conditions and you consent to injunctive or other equitable relief for such violations. Axis Maps may release user information about you if required by law or subpoena.</p>
<h3>Section J - Limitation Of Liability Regarding Use Of Site</h3>
<h4>Limitation of Liability From Use of Site</h4>
<p>AXIS MAPS AND ITS SUBSIDIARIES, AFFILIATES, VENDORS AND/OR LICENSORS AND OTHER THIRD PARTIES MENTIONED ON THIS SITE ARE NEITHER RESPONSIBLE NOR LIABLE FOR ANY INJURIES, DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY, PUNITIVE, OR OTHER DAMAGES WHATSOEVER (INCLUDING, WITHOUT LIMITATION, THOSE RESULTING FROM LOST PROFITS, LOST DATA, OR BUSINESS INTERRUPTION) ARISING OUT OF OR RELATING IN ANY WAY TO THE SITE OR INABILITY TO USE THE SITE, SITE-RELATED SERVICE, CONTENT OR INFORMATION CONTAINED WITHIN THE SITE,  ANY USE, PERFORMANCE, OR POSSESSION OF THIS SITE, ANY HYPERLINKED WEB SITE, ANY DEFECT IN THE SITE OR ITS CONTENTS, AND/OR ANY BREACH OF THESE TERMS AND CONDITIONS. THIS LIMITATION APPLIES (A) WHETHER THE ALLEGED CLAIMS OR DAMAGES ARE BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY AND (B) REGARDLESS OF WHETHER OR NOT AXIS MAPS HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. </p>
<p>YOUR SOLE REMEDY FOR DISSATISFACTION WITH THE SITE, SITE-RELATED SERVICES, AND/OR HYPERLINKED WEB SITES IS TO STOP USING THE SITE AND/OR THOSE SERVICES.  CERTAIN STATE LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES.  SOME OR ALL OF THE ABOVE DISCLAIMERS, EXCLUSIONS, OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MIGHT HAVE ADDITIONAL RIGHTS. IF THE EXCLUSION OF WARRANTY OR LIMITATION OF LIABILITY IS HELD INAPPLICABLE OR UNENFORCEABLE FOR ANY REASON, THEN AXIS MAPS, AND ITS SUBSIDIARIES, AFFILIATES, VENDORS AND/OR LICENSORS AND OTHER THIRD PARTIES MENTIONED ON THIS SITE MAXIMUM LIABILITY FOR ANY TYPE OF DAMAGES SHALL NOT EXCEED THE AMOUNT OF ANY SUBSCRIPTION OR MEMBERSHIP FEE WHICH YOU MAY HAVE PAID FOR THE SERVICE.</p>
<h3>Section K - Indemnity</h3>
<h4>Indemnity</h4>
<p>You agree to indemnify and hold Axis Maps, and its subsidiaries, affiliates, officers, agents, vendors, licensors, and other partners and employees, harmless from any loss, liability, injury (including injuries resulting in death), claim, or demand, including reasonable attorneys' fees and costs, of any kind due to, arising out of, or relating to your use of the Site or its content, including also your use of the Site to provide a link to another site or to upload content or other information to the Site, or your breach of the Terms and Conditions.</p>
<h3>Section L - Accuracy and Integrity of Information</h3>
<h4>Accuracy and Integrity of Information  </h4>
<p>Although Axis Maps attempts to ensure the integrity and accurateness of the Site, it makes no guarantees whatsoever as to the correctness or accuracy of the Site.  It is possible that the Site could include typographical errors, inaccuracies or other errors, and that unauthorized additions, deletions and alterations could be made to the Site by third parties.  In the event that an inaccuracy arises, please inform Axis Maps so that it can be corrected.  Information contained on the Site may be changed or updated without notice.</p>
<h3>Section M - Visitor/Member Chat Rooms And Other Interactive Areas</h3>
<h4>Forums and Other Interactive Areas</h4>
<p>You may post comments, and other content, submit suggestions, ideas, comments, questions, or other information, so long as the content is not illegal, vulgar, obscene, sexually explicit, threatening, harmful, defamatory, harassing, abusive, invasive of privacy, infringing of intellectual property rights, or otherwise injurious to third parties or objectionable, and does not consist of or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings, or any form of spam.  You may not use a false e-mail address, impersonate any person or entity, or otherwise mislead as to the origin of the content. </p>
<p>Axis Maps reserves the right, but is not obligated to, monitor, filter, or review any areas of the Site, including the conduct, where visitors or users transmit or post communications, content, or communicate solely with each other, including, but not limited to, chat rooms, bulletin boards, and other user forums, and the content of any such communications.  Axis Maps, however, will have no liability related to the content of any such communications, whether or not arising under the laws of copyright, libel, privacy, obscenity, or otherwise. Axis Maps retains the right to remove, in its sole discretion, communications that include any material deemed abusive, defamatory, obscene, or otherwise inappropriate. The maker of any such material agrees to indemnify and hold Axis Maps harmless from and against any claim or suit, including damages, costs and attorney fees, brought by any governmental agency or third party as a result of the making of such material.</p>
<p>By providing these materials to Axis Maps, including by submitting or uploading content or materials for use on the Site, you represent and warrant that you are, or the owner of all rights to such content or materials, has expressly granted Axis Maps the right to use all or any part of the content or materials at its sole discretion by any method now existing or later developed. You agree that you shall waive all claims and have no recourse against Axis Maps for any alleged or actual infringement or misappropriation of any proprietary rights in any communication, content, or material submitted to Axis Maps.</p>
<p>As part of the services offered by Axis Maps, we provide the ability for users to generate email and other types of messages (that may include links to maps, directions, or other site services or information) from our Site. Except as set forth herein, Axis Maps is not affiliated with the sender or recipient of any of these email or other messages. When using these message services, you specifically agree that Axis Maps is not responsible or liable to you or anyone else for any unlawful, harassing, defamatory, abusive, threatening, harmful, vulgar, obscene, sexually explicit or otherwise objectionable conduct or speech of any other party on or through the Site, or for any infringement or violation of another's rights by any other party on the Site, including but not limited to intellectual property rights, rights of publicity, or rights of privacy.</p>
<h3>Section N - DMCA Policy</h3>
<h4>DMCA Policy</h4>
<p>As provided in the Digital Millennium Copyright Act (DMCA), we have designated the following individual for notification of potential copyright infringement regarding the Site:</p>
<p>David Heyman<br />19104 Annapolis Way<br />Montgomery Village, MD 20886<br />dave@axismaps.com<br />+1 608 301 5320</p>
<p>If you believe any service or user content available through the Site infringes a copyright, please provide the following information to the person identified above (17 U.S.C. ¤ 512):</p>
	<ol>
		<li>A physical or electronic signature of the copyright owner or authorized agent; </li>
		<li>Identification of the copyrighted work(s) claimed to have been infringed; </li>
		<li>Identification of the material that is claimed to be infringing or to be the subject of the infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit us to locate the material; </li>
		<li>Information regarding how we may contact you (e.g., mailing address, telephone number, e-mail address); </li>
		<li>A statement that the copyright owner or its authorized agent has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and </li>
		<li>A statement that the information in the notification is accurate, and made under penalty of perjury, and, if an agent is providing the notification, a statement that the agent is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</li>
	</ol>
<h3>Section O - Links or Pointers to other Sites</h3>
<h4>Links or Pointers to Other Sites</h4>
<p>The Site may automatically produce search results that reference and/or link to third party web sites throughout the World Wide Web. Axis Maps makes no representations whatsoever about any other web site that you may access through this Site.  When you access a non-Axis Maps site, please understand that it is independent from Axis Maps, and that Axis Maps has no control over the content on that Web site.  In addition, a hyperlink to a non-Axis Maps Web site does not mean that Axis Maps endorses or accepts any responsibility for the content, or the use, of the linked site.  It is up to you to take precautions to ensure that whatever you select for your use or download is free of such items as viruses, worms, Trojan horses, and other items of a destructive nature.  If you decide to access any of the third party sites linked to this Site, you do this entirely at your own risk.</p>
<h3>Section P - Advertising</h3>
<h4>Advertising</h4>
<p>The Site may contain advertisement and/or sponsorship. The advertisers and/or sponsors that provide these advertisements and sponsorship are solely responsible for insuring that the materials submitted for inclusion on the Site are accurate and comply with all applicable laws. Axis Maps is not responsible for the acts or omissions of any advertiser or sponsor.</p>
<h3>Section Q - Termination</h3>
<h4>Termination</h4>
<p>Axis Maps reserves the right, in its sole discretion and without liability to you, to change, suspend, or terminate your access to all or part of this Site, or discontinue any aspect of the Site, with or without cause, and with or without notice. </p>
<h3>Section R - Statute of Limitations</h3>
<h4>Statute of Limitations</h4>
<p>Any cause of action brought by you against us or our affiliated parties must be instituted within one (1) year after the cause of action arises or be deemed forever waived and barred.</p>
<h3>Section S - Choice of Law and Venue</h3>
<h4>Choice of Law and Venue</h4>
<p>This Site is controlled by Axis Maps from its offices within the state of Wisconsin, of the United States of America.  It can be accessed from all fifty states, as well as from other countries around the world.  Each of these places has laws that may differ from those of Wisconsin.  By accessing this Site, both you and Axis Maps agree that the statutes and laws of the state of Wisconsin will apply to all matters related to these Terms and Conditions and the use of the Site, without regard to conflicts of laws or principles thereof.  Each party also agrees and hereby submits to the exclusive personal jurisdiction and venue of the state and federal courts sitting in Dane County, Wisconsin, and waives any jurisdictional, venue or inconvenient form of objections to such courts. </p>
<p>Axis Maps makes no representation that materials on the Site are appropriate or available for use in other locations, and accessing them from territories where their contents are illegal is prohibited.  Those who choose to access this Site from other locations do so on their own initiative and are responsible for compliance with local laws. </p>
<h3>Section T - International Use</h3>
<h4>International Use</h4>
<p>By choosing to access the Site from any location other than the United States, you accept full responsibility for compliance with all local laws that are applicable. Axis Maps makes no representation that materials on the Site are appropriate or available for use in locations outside the United States, and accessing them from territories where their contents are illegal is prohibited.  You may not use, export or re-export any materials from this Site in violation of any applicable laws or regulations, including, but not limited to, any United States export laws and regulations.</p>
<h3>Section U - Severability</h3>
<h4>Severability</h4>
<p>In the event that any of the Terms and Conditions are held by a court or other tribunal of competent jurisdiction to be unenforceable, such provisions shall be limited or eliminated to the minimum extent necessary so that these Terms and Conditions shall otherwise remain in full force and effect.</p>
<h3>Section V - Additional Terms Applicable to Online Subscribers</h3>
<h4>Additional Terms Applicable to Online Subscribers</h4>
<p>The following terms are applicable to online subscribers to Axis Maps:</p>
<p>As part of the registration process for an online subscription, you must select a password and a subscriber ID, as well as provide us with certain registration information, all of which must be accurate and updated.  It shall be a breach of the Terms and Conditions to select or utilize a user name (i) of another person with intent to impersonate that person, (ii) in which another person has rights, if you do not have that person's authorization to use such name, or (iii) that Axis Maps in its sole discretion deems offensive. You are solely responsible for maintaining the confidentiality of any password you use to access the online services, and agree that Axis Maps shall have no obligations with regard thereto. Please notify info@axismaps.com of any potential unauthorized use(s) of your account, or breach of security.</p>
<p>Axis Maps charges fees for access to portions of the Site.  You agree to pay for your subscription the amounts set forth on the online print and subscription form ("Fees").  You shall pay all Fees incurred through your account at the rates in effect for the billing period in which such Fees are incurred.  You shall pay all applicable sales and use taxes relating to your use of the Site. </p>
<p>You may terminate your online subscription at any time by sending email to: support@indiemapper.com.  If Axis Maps terminates your use of the Site or your online subscription, you shall not be entitled to a refund of any Fees.</p>
<p>Axis Maps will automatically renew your subscription or membership at the end of each term and bill the then-current renewal fee to the credit card we have on file for your account. You may update the credit card on file by updating your account online.</p>
<h3>Section W - Entire Agreement</h3>
<h4>Entire Agreement</h4>
<p>These Terms and Conditions constitute the entire agreement between Axis Maps and you pertaining to the subject matter hereof.  In its sole discretion, Axis Maps may from time-to-time revise these Terms and Conditions by updating this posting.  You should, therefore, periodically visit this page to review the current Terms and Conditions, so you are aware of any such revisions to which you are bound.  Certain provisions of these Terms and Conditions may be superseded by expressly designated legal notices or terms located on particular pages within this Site.</p>
<p>Effective Date of these Web Site Terms and Conditions of Use:   April 12, 2010.</p>